# Generated by Django 3.1.4 on 2021-02-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videopage',
            options={'verbose_name': 'Video Page', 'verbose_name_plural': 'Videos Pages'},
        ),
    ]
