# Generated by Django 3.1.4 on 2021-03-08 04:28

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20210222_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopage',
            name='body',
            field=wagtail.core.fields.RichTextField(default='Test'),
            preserve_default=False,
        ),
    ]
