apiVersion: apps/v1
kind: Deployment
metadata:
  name: wag-deployment
  labels:
    app: wagtail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wagtail
  template:
    metadata:
      labels:
        app: wagtail
    spec:
      containers:
      - name: wagtail
        image: wag
        imagePullPolicy: Never
      restartPolicy: Always
